### ISSUE TITLE
Could you please share your visualization code?

### ISSUE THREAD

**Issue by Rurouni-z** [marios2019/CSN#2]
I didn't see how to visualize in the readme, so I assumed there was no code for visualization

**Comment by marios2019** [comment]
Hello! At the moment, we do not have available code for visualizing results, such as point cloud semantic label predictions or retrieved neighbors. However, I plan to refine several scripts and add them to the repository soon to facilitate this feature.

**Comment by Rurouni-z** [comment]
> Hello! At the moment, we do not have available code for visualizing results, such as point cloud semantic label predictions or retrieved neighbors. However, I plan to refine several scripts and add them to the repository soon to facilitate this feature.

thanku very much!

**Comment by Rurouni-z** [comment]
> Hello! At the moment, we do not have available code for visualizing results, such as point cloud semantic label predictions or retrieved neighbors. However, I plan to refine several scripts and add them to the repository soon to facilitate this feature.

I'm also wondering if these codes can be used with my own **plant** data set, which contains three labels
