### ISSUE TITLE
reproduce the code found that some results were inconsistent

### ISSUE THREAD

**Issue by Rurouni-z** [marios2019/CSN#3]
first change the **test_hrnet.sh**: change "$(git rev-parse HEAD)" to "VERSION1" or anything
copy and change these line:
KEY_SHAPE=1
BASE_DIR=./outputs/$DATASET/$MODEL/$CATEGORY-$OPTIMIZER-l$LR-b$BATCH_SIZE **-k$KEY_SHAPE**-$SCHEDULER-e$MAX_EPOCH-$EXPERIMENT-$INPUT_FEAT

i test the HRNetSimCSN3S, here is the result:
![image](https://github.com/marios2019/CSN/assets/53394846/d1c874a6-37bb-46b3-9bc6-9afad96d818b)
![image](https://github.com/marios2019/CSN/assets/53394846/2c230146-4a8c-47c1-bc4b-a7e2cddde2ea)

Also, I feel like this CSA idea might be helpful for my thesis, so thanku for your work!

**Comment by marios2019** [comment]
For evaluating the Cross-Shape Networks you will need to use the `testing_csn.sh` script as described [here](https://github.com/marios2019/CSN/tree/main/MinkowskiNet#minkhrnetcsn-1).

**Comment by Rurouni-z** [comment]
> For evaluating the Cross-Shape Networks you will need to use the `testing_csn.sh` script as described [here](https://github.com/marios2019/CSN/tree/main/MinkowskiNet#minkhrnetcsn-1).

yeah, it is my fault, i am trying to rerun this scipt, and it is truely slow :) thanku for your great work

**Comment by Rurouni-z** [comment]
> > For evaluating the Cross-Shape Networks you will need to use the `testing_csn.sh` script as described [here](https://github.com/marios2019/CSN/tree/main/MinkowskiNet#minkhrnetcsn-1).
> 
> yeah, it is my fault, i am trying to rerun this scipt, and it is truely slow :) thanku for your great work

excellent work!
![image](https://github.com/marios2019/CSN/assets/53394846/5418697a-c456-4d2b-aaf6-4e6faabd95a4)

**Comment by marios2019** [comment]
> > For evaluating the Cross-Shape Networks you will need to use the `testing_csn.sh` script as described [here](https://github.com/marios2019/CSN/tree/main/MinkowskiNet#minkhrnetcsn-1).
> 
> yeah, it is my fault, i am trying to rerun this scipt, and it is truely slow :) thanku for your great work

Thank you for your interest in our work. Considering inference time, it depends on the number of training shapes used for retrieval (see **Computation** paragraph in **Section 4. Results** of the paper):

_During inference, the time required per test shape exhibits linear complexity wrt the number of training shapes used for retrieval. In our experiments, testing time ranges from 0.7 sec (“Dish” class with the smallest number of shapes) to 7.8 sec (“Table” class with the largest number of shapes)._
